version: '3.7'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
    container_name: es01
    environment:
      - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  db: 
    image: mysql/mysql-server:latest
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: chat_system_app
        MYSQL_USER: root
        MYSQL_PASSWORD: root
    ports:
        - "3306"
    expose:
        - "3306"
    command: --default-authentication-plugin=mysql_native_password
  redis:
    image: redis:alpine
    restart: always
    ports:
      - '6380:6379'
    volumes:
      - ./volumes/redis-data:/data
    command: redis-server
  rabbitmq:
    image: rabbitmq:3.9-management-alpine
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./volumes/rabbitmq:/var/lib/rabbitmq
  web:
    build: .
    command: bash -c "bash ./init.sh && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      - REDIS_HOST=redis
      - RABBITMQ_HOST=rabbitmq
      - ES_HOST=es01
      - DB_USER=root
      - DB_NAME=chat_system_app
      - DB_PASSWORD=root
      - DB_HOST=db
    depends_on:
      - db
      - redis
    links:
      - db
    ports:
      - '3000:3000'
    volumes:
      - .:/myapp
  worker:
    build: .
    command: bundle exec rake sneakers:run
    volumes:
      - .:/myapp
    depends_on:
      - web
      - rabbitmq
    links:
      - db
      - rabbitmq
    environment:
      - WORKERS=ChatWorker,MessageWorker
      - DB_USER=root
      - DB_NAME=chat_system_app
      - DB_PASSWORD=root
      - DB_HOST=db
      - REDIS_HOST=redis
      - RABBITMQ_HOST=rabbitmq
      - ES_HOST=es01
  # rufus_worker:
  #   build: .
  #   command: bundle exec rake rufus_job
  #   depends_on:
  #     - web
  #     - db
volumes:
  redis:
  rabbitmq:
  data01:
  myapp:
# networks:
#   host:
#     name: 'chat-system-default'