version: '3.7'
services:
  es:
    image: elasticsearch:5.4.0-alpine
    restart: always
    ports:
      - "9300:9200"
    volumes:
      - ./volumes/es:/usr/share/elasticsearch/data
  db:
    image: mysql:8.0.20
    volumes:
      - mysql:/var/lib/mysql:delegated
    restart: always
    ports:
      - '3307:3306'
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
  redis:
    image: redis:alpine
    restart: always
    ports:
      - '6380:6379'
    volumes:
      - ./volumes/redis-data:/data
    command: redis-server 
  rabbitmq:
    image: rabbitmq:3.9-management-alpine
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./volumes/rabbitmq:/var/lib/rabbitmq
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && rake db:create db:migrate && bundle exec rails s -p 3000 -b '0.0.0.0'"
    tty: true
    stdin_open: true
    environment:
      - REDIS_HOST=redis
      - RABBITMQ_HOST=rabbitmq
    links:
      - db
      - redis
      - rabbitmq
    depends_on:
      - db
      - redis
      - rabbitmq
    ports:
      - '3000:3000'
    volumes:
      - .:/app:cached
      - bundle:/usr/local/bundle:delegated
      - node_modules:/app/node_modules
      - tmp-data:/app/tmp/sockets
  worker:
    build: .
    command: rake sneakers:run
    restart: always
    volumes:
      - .:/app
    links:
      - rabbitmq
      - db
      - redis
      - es
    depends_on:
      - web
      - rabbitmq
    environment:
      - WORKERS=ChatWorker,MessageWorker
      - MYSQL_HOST=db
      - REDIS_HOST=redis
      - RABBITMQ_HOST=rabbitmq
      - ES_HOST=es
volumes:
  mysql:
  bundle:
  node_modules:
  tmp-data:
  redis:
  rabbitmq:

