version: '3.7'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
    container_name: es01
    environment:
      - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    command: ['mysqld', '--character-set-server=utf8mb4','--default-authentication-plugin=mysql_native_password' ,'--collation-server=utf8mb4_unicode_ci']
    environment:
     - MYSQL_ALLOW_EMPTY_PASSWORD=1
     - MYSQL_ROOT_HOST=%
  redis:
    image: redis:alpine
    restart: always
    ports:
      - '6380:6379'
    volumes:
      - ./volumes/redis-data:/data
    command: redis-server
  rabbitmq:
    image: rabbitmq:3.9-management-alpine
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./volumes/rabbitmq:/var/lib/rabbitmq
  web:
    build: .
    command: bash -c "bash ./init.sh && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      - REDIS_HOST=redis
      - RABBITMQ_HOST=rabbitmq
      - ES_HOST=es01
      - MYSQL_USERNAME=root
      - MYSQL_HOST=db
    depends_on:
      - db
      - redis
    ports:
      - '3000:3000'
    volumes:
      - .:/myapp
  worker:
    build: .
    command: bundle exec rake sneakers:run
    restart: always
    volumes:
      - .:/myapp
    links:
      - db
      - redis
      - es01
      - rabbitmq
    depends_on:
      - web
    environment:
      - WORKERS=ChatWorker,MessageWorker
      - MYSQL_HOST=db
      - REDIS_HOST=redis
      - RABBITMQ_HOST=rabbitmq
      - ES_HOST=es01
  rufus_worker:
    build: .
    command: bundle exec rake rufus_job
    depends_on:
      - web
      - db
volumes:
  redis:
  rabbitmq:
  data01:
  myapp:
